[package]
name = "pollination-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
pollination-simulator = { "path" = "../pollination-simulator" }
pollination = { "path" = "../pollination-core" }
rand = "0.9.2"
uuid = { version = "1.16.0", features = ["serde", "v4"] }
